-- CREACION DE LA BASE DE DATOS (SI NO EXISTE)
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'dbCatalogo')
BEGIN
    CREATE DATABASE dbCatalogo;
END
GO

-- USO DE LA BASE DE DATOS
USE dbCatalogo;
GO

-- ELIMINAR LAS TABLAS SI YA EXISTEN
IF OBJECT_ID('PUBLICACIONES', 'U') IS NOT NULL
    DROP TABLE PUBLICACIONES;
GO

IF OBJECT_ID('IMAGENES', 'U') IS NOT NULL
    DROP TABLE IMAGENES;
GO

IF OBJECT_ID('PRODUCTOS', 'U') IS NOT NULL
    DROP TABLE PRODUCTOS;
GO

IF OBJECT_ID('FABRICANTES', 'U') IS NOT NULL
    DROP TABLE FABRICANTES;
GO

IF OBJECT_ID('CATEGORIAS', 'U') IS NOT NULL
    DROP TABLE CATEGORIAS;
GO

IF OBJECT_ID('ESTADOS', 'U') IS NOT NULL
    DROP TABLE ESTADOS;
GO

-- CREACION DE LAS TABLAS
CREATE TABLE ESTADOS 
(
    ID INT NOT NULL IDENTITY(1,1),
    NOMBRE NVARCHAR(25) NOT NULL,
    CONSTRAINT PK_ESTADOS PRIMARY KEY CLUSTERED (ID)
);
GO

CREATE TABLE CATEGORIAS
(
    ID INT NOT NULL IDENTITY(1,1),
    CATEGORIA NVARCHAR(25) NOT NULL,
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY CLUSTERED (ID)
);
GO

CREATE TABLE FABRICANTES
(
    ID INT NOT NULL IDENTITY(1,1),
    NOMBRE NVARCHAR(45) NOT NULL,
    CONTACTO NVARCHAR(30) NOT NULL,
    CONSTRAINT PK_FABRICANTES PRIMARY KEY CLUSTERED (ID)
);
GO

CREATE TABLE PRODUCTOS
(
    ID INT NOT NULL IDENTITY(1,1),
    NOMBRE NVARCHAR(40) NOT NULL,
    CODIGO NVARCHAR(10) NOT NULL,
    CANTIDAD INT,
    PRECIO MONEY NOT NULL,
    COSTO MONEY NOT NULL,
    FABRICANTE INT NOT NULL,
    CATEGORIA INT NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY CLUSTERED (ID),
    CONSTRAINT FK_FABRICANTE FOREIGN KEY (FABRICANTE) REFERENCES FABRICANTES(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIAS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

CREATE TABLE IMAGENES
(
    ID INT NOT NULL IDENTITY(1,1),
    ARCHIVO NVARCHAR(25) NOT NULL,
    INFORMACION NVARCHAR(100),
    PRODUCTO INT NOT NULL,
    CONSTRAINT PK_IMAGENES PRIMARY KEY CLUSTERED (ID),
    CONSTRAINT FK_IMAGENES_PRODUCTO FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTOS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

CREATE TABLE PUBLICACIONES
(
    ID INT NOT NULL IDENTITY(1,1),
    FECHA DATETIME DEFAULT GETDATE(),
    TITULO NVARCHAR(50) NOT NULL,
    DESCRIPCION NVARCHAR(100),
    PRODUCTO INT NOT NULL,
    ESTADO INT NOT NULL,
    CONSTRAINT PK_PUBLICACIONES PRIMARY KEY CLUSTERED (ID),
    CONSTRAINT FK_PUBLICACIONES_PRODUCTO FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTOS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT FK_PUBLICACIONES_ESTADO FOREIGN KEY (ESTADO) REFERENCES ESTADOS(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO

-- INSERTAR VALORES A LAS TABLAS
IF NOT EXISTS (SELECT * FROM ESTADOS)
BEGIN
    INSERT INTO ESTADOS (NOMBRE) VALUES
    ('En stock'), 
    ('Agotado');
END
GO

IF NOT EXISTS (SELECT * FROM CATEGORIAS)
BEGIN
    INSERT INTO CATEGORIAS (CATEGORIA) VALUES
    ('Electronica'),
    ('Ropa'),
    ('Muebles');
END
GO

-- Insertar valores en FABRICANTES solo si no existen
IF NOT EXISTS (SELECT * FROM FABRICANTES)
BEGIN
    INSERT INTO FABRICANTES (NOMBRE, CONTACTO) VALUES
    ('Apple', 'customer.service@apple.com'),
    ('Bershka', 'customer.service@bershka.com'),
    ('IKEA', 'customer.service@ikea.com');
END
GO

IF NOT EXISTS (SELECT * FROM PRODUCTOS)
BEGIN
    INSERT INTO PRODUCTOS (NOMBRE, CODIGO, CANTIDAD, PRECIO, COSTO, FABRICANTE, CATEGORIA) VALUES
    ('iPhone 15 Pro Max', 'IP15PM256', 10, 1099.99, 950.00, 1, 1),
    ('Vestido a cuadros azul', 'VD2024', 20, 49.99, 25.00, 2, 2),
    ('Silla de oficina IKEA', 'SILLA2024', 15, 199.99, 150.00, 3, 3),
    ('Bolso de mano pequeño', 'BOLSO2024', 30, 29.99, 15.00, 2, 2);
END
GO

IF NOT EXISTS (SELECT * FROM IMAGENES)
BEGIN
    INSERT INTO IMAGENES (ARCHIVO, INFORMACION, PRODUCTO) VALUES
    ('iphone15.png', '####', 1),
    ('vestidoss2024.jpeg', '####', 2),
    ('vestidoss2024-01.jpeg', '####', 2),
    ('silla.png', '####', 3),
    ('bolso.png', '####', 4);
END
GO

IF NOT EXISTS (SELECT * FROM PUBLICACIONES)
BEGIN
    INSERT INTO PUBLICACIONES (FECHA, TITULO, DESCRIPCION, PRODUCTO, ESTADO) VALUES
    ('2024-09-02', 'Apple iPhone 15 Pro Max (256 GB)', 'Disponible nuevo iPhone 15 Pro Max', 1, 1),
    ('2024-08-26', 'Vestido a cuadros azul', 'Rebajas colección de verano', 2, 2),
    ('2024-06-17', 'Increíble silla de oficina IKEA', 'Super cómoda y al mejor precio', 3, 1),
    ('2024-05-15', 'Silla ergonomica de oficina', 'Mejora tus condiciones de trabajo con esta silla', 3, 1),
    ('2024-05-30', 'Bolso de mano pequeño', 'Alto x Ancho x Fondo: 14 x 6 x 8 cm', 4, 1);
END
GO